use lib "./inc";
our %PREREQ_PM;
BEGIN {
   %PREREQ_PM= (
      #'ExtUtils::Depends' => '0.405',
      'ExtUtils::CBuilder' => '0.2800',
   );
   # If the prereqs for this script are missing,
   # write out a Makefile that tells CPAN to install them
   my $use_prereqs_code= join('', map { "use $_ $PREREQ_PM{$_}; " } keys %PREREQ_PM).'1;';
   print $use_prereqs_code."\n";
   unless (eval $use_prereqs_code) {
      warn "$@\n";
      WriteMakefile(
         NAME         => 'Crypt::MultiKey',
         PREREQ_FATAL => 1,
         PREREQ_PM    => \%PREREQ_PM,
      );
      exit 1; # not reached
   }
}

require ExtUtils::Depends;
require ExtUtils::CFeatureTest;

my $dep= ExtUtils::Depends->new('Crypt::MultiKey', 'Crypt::SecretBuffer');
my $test= ExtUtils::CFeatureTest->new;

$test->header('stdbool.h');
$test->feature(HAVE_BOOL      => 'bool x= true; return x == false;');

$test->feature(HAVE_LIBSSL    => 'unsigned char buf[1]; return RAND_bytes(buf, 1) == 1? 0 : 1;',
               { h => 'openssl/rand.h', -l => 'ssl' });

$test->write_config_header('CryptMultiKey_config.h');
$test->export_deps($dep);

$dep->install('cmk.h');
$dep->add_xs('CryptMultiKey.xs');
$dep->add_pm(map { my $n= $_; $n =~ s/^lib/\$(INST_LIB)/; $_ => $n } <lib/*/*.pm>, <lib/*/*/*.pm>);
$dep->add_typemaps('typemap');
$dep->save_config('InstallFiles.pm');
